package com.cryptomacro.app.domain.model

/** BEGINNER: Hard-coded Top 50 US tickers. toAsset("AAPL","Apple") → id stock-aapl, yahooSymbol AAPL. */

/** Largest listed US names by market cap — Top 50 stocks with live quotes. */
object TopStocks {
    val tickers: List<Pair<String, String>> = listOf(
        "AAPL" to "Apple",
        "NVDA" to "NVIDIA",
        "MSFT" to "Microsoft",
        "GOOGL" to "Alphabet",
        "AMZN" to "Amazon",
        "META" to "Meta Platforms",
        "TSLA" to "Tesla",
        "BRK-B" to "Berkshire Hathaway",
        "AVGO" to "Broadcom",
        "LLY" to "Eli Lilly",
        "JPM" to "JPMorgan Chase",
        "V" to "Visa",
        "WMT" to "Walmart",
        "XOM" to "Exxon Mobil",
        "UNH" to "UnitedHealth",
        "MA" to "Mastercard",
        "ORCL" to "Oracle",
        "COST" to "Costco",
        "HD" to "Home Depot",
        "PG" to "Procter & Gamble",
        "NFLX" to "Netflix",
        "JNJ" to "Johnson & Johnson",
        "BAC" to "Bank of America",
        "ABBV" to "AbbVie",
        "CRM" to "Salesforce",
        "KO" to "Coca-Cola",
        "CVX" to "Chevron",
        "AMD" to "AMD",
        "PEP" to "PepsiCo",
        "TMO" to "Thermo Fisher",
        "CSCO" to "Cisco",
        "WFC" to "Wells Fargo",
        "LIN" to "Linde",
        "ACN" to "Accenture",
        "MCD" to "McDonald's",
        "GE" to "GE Aerospace",
        "ABT" to "Abbott",
        "PM" to "Philip Morris",
        "IBM" to "IBM",
        "MRK" to "Merck",
        "DIS" to "Disney",
        "CAT" to "Caterpillar",
        "RTX" to "RTX",
        "GS" to "Goldman Sachs",
        "INTU" to "Intuit",
        "QCOM" to "Qualcomm",
        "AXP" to "American Express",
        "AMGN" to "Amgen",
        "NOW" to "ServiceNow",
        "UBER" to "Uber",
    )

    fun toAsset(symbol: String, name: String) = AssetDefinition(
        id = "stock-${symbol.lowercase()}",
        symbol = symbol,
        name = name,
        category = AssetCategory.EQUITY,
        yahooSymbol = symbol,
        tag = CoinTag.BENCHMARK,
        unit = AssetUnit.USD,
        description = "Listed equity",
    )
}
